openapi: "3.0.2"
info:
  description: "Synergy! mail delivery api."
  version: "1.0.3"
  title: "Synergy! mail delivery api."
  termsOfService: ""
  x-audience: "https://mail.paas.crmstyle.com"
  contact:
    email: "api-tech-support@synergy101.jp"
  license:
    name: "Synergy"
    url: "https://form.synergy-marketing.co.jp/fcnts/euz/mailapi_agreement.html"
servers:
- url: "https://mail.paas.crmstyle.com/e"
paths:
  /tymail/v1/{user}/mail/deliveries/{taskId}:
    get:
      summary: "Get a delivery task status"
      operationId: "getDeliveryStatus"
      security:
      - mail_oauth:
        - "mail:send"
    delete:
      summary: "Delete a delivery task"
      operationId: "deleteDeliveryTask"
      security:
      - mail_oauth:
        - "mail:send"
  /tymail/v1/{user}/mail/deliveries:
    post:
      summary: "start mail delivery"
      operationId: "startMailDelivery"
      security:
      - mail_oauth:
        - "mail:send"
  /tymail/v1/{user}/mail/deliveries/{taskId}/send:
    post:
      summary: "start prepared mail delivery"
      operationId: "startPreparedMailDelivery"
      security:
      - mail_oauth:
        - "mail:send"
  /tymail/v1/{user}/mail/deliveries/new:
    post:
      summary: "create mail delivery setting"
      operationId: "createMailDeliverySetting"
      security:
      - mail_oauth:
        - "mail:send"
  /tymail/v1/{user}/mail/deliveries/reserve/sendlists:
    post:
      summary: "create send list"
      operationId: "createSendList"
      security:
      - mail_oauth:
        - "mail:send"
  /tymail/v1/{user}/mail/deliveries/reserve/sendlists/{sendListId}:
    get:
      summary: "get send list"
      operationId: "getSendList"
      security:
      - mail_oauth:
        - "mail:send"
  /tymail/v1/{user}/mail/deliveries/reserve:
    post:
      summary: "reserve mail delivery"
      operationId: "reserveMailDelivery"
      security:
      - mail_oauth:
        - "mail:send"
  /tymail/v1/{user}/mail/deliveries/{taskId}/opens:
    get:
      summary: "Get the mail open results"
      operationId: "getDeliveryMailOpenResults"
      security:
      - mail_oauth:
        - "mail:result"
  /tymail/v1/{user}/mail/deliveries/{taskId}/clicks:
    get:
      summary: "Get the mail click results"
      operationId: "getDeliveryMailClickResults"
      security:
      - mail_oauth:
        - "mail:result"
  /tymail/v1/{user}/mail/deliveries/{taskId}/errors:
    get:
      summary: "Get the mail error results"
      operationId: "getDeliveryMailErrorResults"
      security:
      - mail_oauth:
        - "mail:result"
  /tymail/v1/{user}/mail/deliveries/{taskId}/results:
    get:
      summary: "Get the mail results"
      operationId: "getDeliveryMailResults"
      security:
      - mail_oauth:
        - "mail:result"
  /tymail/v1/{user}/mail/deliveries/errors/all:
    get:
      summary: "Get all mail error results"
      operationId: "getAllDeliveryMailErrorResults"
      security:
      - mail_oauth:
        - "mail:result"
components:
  securitySchemes:
    mail_oauth:
      type: oauth2
      description: mail auth
      flows:
        clientCredentials:
          tokenUrl: "https://auth.paas.crmstyle.com/oauth2/token"
          refreshUrl: "https://auth.paas.crmstyle.com/oauth2/token"
          scopes:
            mail:send: "delivery"
            mail:result: "get the delivery results"
